name: homemadefood-db

services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: homemadefood-db.dev.postgres
    # command: '-d 1' # set debug-level
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '54320:5432'
    restart: always
    healthcheck:
      # Github issue with posgres health check command `pg_isready`: https://github.com/peter-evans/docker-compose-healthcheck/issues/16#issuecomment-1420377736
      test: ['CMD-SHELL', 'psql -h localhost -U $POSTGRES_USER -d $POSTGRES_DB -c "select 1"']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  # Refs:
  # https://github.com/timowilhelm/local-neon-http-proxy
  # https://neon.tech/guides/local-development-with-neon
  # NOTE: this proxy does NOT work at the moment due to `drizzle-orm/neon-http` always tries to connect to internet (Neon DB server) no matter which DB URL is used (`drizzle-orm/neon-http` evens throw an error if DB URL's host is localhost).
  # neon_proxy:
  #   image: ghcr.io/timowilhelm/local-neon-http-proxy:main
  #   container_name: homemadefood-db.dev.neon_proxy
  #   environment:
  #     - PG_CONNECTION_STRING=${PG_CONNECTION_STRING}
  #   ports:
  #     - '4444:4444'
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #       restart: true

volumes:
  pgdata:
