name: 📄 Deploy DB documentation

on:
  push:
    branches:
      - main
    paths:
      - 'app/.server/db/schema/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/.server/db/schema/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      sql: ${{ steps.filter.outputs.sql }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      # Checks to see if any files in the PR match one of the listed file types.
      # We can check if a file with a listed file type is in the PR by doing:
      # if: ${{ steps.filter.outputs.sql == 'true' }}
      # This will return true if there's a sql file that was changed
      # in the PR. If there is any, run the relevant commands. Otherwise, skip.
      - name: 📂 Get changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            sql:
              - 'app/.server/db/sql/**.sql'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.sql == 'true' }}
    runs-on: ubuntu-latest
    env:
      DBML_FILE_PATH: app/.server/db/schema.dbml
      SQL_FILE_PATH: app/.server/db/sql/schema.sql
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: package.json

      - name: 📥 Install dbdocs
        run: npm install -g dbdocs

      - name: 📥 Install @dbml/cli
        run: npm install -g @dbml/cli

      - name: 📄 Generate dbml
        # run: dbdocs db2dbml postgres ${{ secrets.DATABASE_URL }} -o $DBML_FILE_PATH
        run: sql2dbml --postgres $SQL_FILE_PATH -o $DBML_FILE_PATH

      - name: 🔎 Validate dbml
        run: dbdocs validate $DBML_FILE_PATH

      - name: 🌐 Update dbdocs project
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
          DBDOCS_PROJECT_NAME: Homemade food app
        run: dbdocs build $DBML_FILE_PATH --project "$DBDOCS_PROJECT_NAME"
