name: ⚡ Test coverage

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: ⚡ Run Vitest and collect coverage data
    runs-on: ubuntu-22.04
    environment: Test
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Install package manager
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: ⎔ Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: package.json

      - name: 📥 Install deps
        run: pnpm install

      - name: ⚡ Generate test coverage
        run: pnpm run test:coverage --reporter=junit --outputFile=test-report.junit.xml

      - name: 📊 Upload coverage to Codecov
        # if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
